url: https://ws.narvar.qa/api/v1/event/
httpmethod: POST
headers:
  Content-Type: application/json
  Authorization: Basic YWRkYmNjNGZhM2Y3NGRiNDk1MDA3Y2QwZmQ5YTU1ZTk6ZjA1YzEyZGNjNTgzNDQ2OWEzYmQ1Y2IzZjI1MGUxZTM=
json-body-file-path: ../payload.json
json-body-dynamic-fields: 
  - guid
rate: 10 #Vegeta attack rate
duration: 1 #Veteta attack duration